#include "stdafx.h"

Scaleform g_scaleform;

void Scaleform::PrepareInstructionalButtons() {
	m_scaleForm = GRAPHICS::REQUEST_SCALEFORM_MOVIE("instructional_buttons");
	if (GRAPHICS::HAS_SCALEFORM_MOVIE_LOADED(m_scaleForm)) {
		GRAPHICS::DRAW_SCALEFORM_MOVIE_FULLSCREEN(m_scaleForm, 255, 255, 255, 0, 0);
		GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(m_scaleForm, "CLEAR_ALL");
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
		GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(m_scaleForm, "SET_CLEAR_SPACE");
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(200);
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
		GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(m_scaleForm, "SET_MAX_WIDTH");
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_FLOAT(1);
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
		GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(m_scaleForm, "SET_DATA_SLOT_EMPTY");
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
	}
	m_prepared = true;
}

void Scaleform::FinishInstructionalButtons() {

	if (!m_prepared) return;
	if (GRAPHICS::HAS_SCALEFORM_MOVIE_LOADED(m_scaleForm)) {
		GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(m_scaleForm, "DRAW_INSTRUCTIONAL_BUTTONS");
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
		GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(m_scaleForm, "SET_BACKGROUND_COLOUR");
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(/*pRenderer.m_cOutline.m_r*/ 0);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(/*pRenderer.m_cOutline.m_g*/ 0);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(/*pRenderer.m_cOutline.m_b*/ 0);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(80);
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
		m_offset = 0;
	}
	m_prepared = false;
}

void Scaleform::DrawInstructional(String text, String button) {
	if (!m_prepared) return;
	if (GRAPHICS::HAS_SCALEFORM_MOVIE_LOADED(m_scaleForm)) {
		GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(m_scaleForm, "SET_DATA_SLOT");
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(m_offset);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_TEXTURE_NAME_STRING(("t_" + (string)button).c_str());
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_TEXTURE_NAME_STRING(text);
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
		m_offset++;
	}
}

Scaleform* GetScaleform() { return &g_scaleform; }